### ISSUE TITLE
nix build fails when it comes to applying patch to a derivation

### ISSUE THREAD

**Issue by gianarb** [nix-community/naersk#266]
Hello! I put together an easy to reproduce repo when I try to apply a patch to a rust project. I am doing something wrong but I can't figure out what and most likely it is not limited to rust but to how I intend patch? I generated the patch with `git diff -a > path`

https://github.com/gianarb/rust-nix-test

```shell
$ nix build github:gianarb/rust-nix-test
error: builder for '/nix/store/lr2g8s488b3z9bsnfhjw7h5linz306d7-nixtest-deps-0.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > --------------------------
       > |diff --git a/src/main.rs b/src/main.rs
       > |index e7a11a9..da112c2 100644
       > |--- a/src/main.rs
       > |+++ b/src/main.rs
       > --------------------------
       > File to patch:
       > Skip this patch? [y]
       > Skipping patch.
       > 1 out of 1 hunk ignored
       For full logs, run 'nix log /nix/store/lr2g8s488b3z9bsnfhjw7h5linz306d7-nixtest-deps-0.1.0.drv'.
```

**Comment by Patryk27** [comment]
Hi,

The patch cannot be applied because of two reasons:
- your `src/main.rs` file already says `Hello, Mars!` (😇),
- due to a bug, Naresk passes `patches` into some internal derivations it uses -- try adding `singleStep = true;` to your `buildPackage` invocation, that should fix it.

I'll try preparing a fix, so that you don't have to pass `singleStep = true;`, but that should work around the issue for the time being 🙂

**Comment by gianarb** [comment]
Nice! I knew I was doing something silly.

About `main.rs` having the patch already applied you are right, I fixed that and just for the record, the problem persist:

```
$ nix build
error: builder for '/nix/store/lr2g8s488b3z9bsnfhjw7h5linz306d7-nixtest-deps-0.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > --------------------------
       > |diff --git a/src/main.rs b/src/main.rs
       > |index e7a11a9..da112c2 100644
       > |--- a/src/main.rs
       > |+++ b/src/main.rs
       > --------------------------
       > File to patch:
       > Skip this patch? [y]
       > Skipping patch.
       > 1 out of 1 hunk ignored
       For full logs, run 'nix log /nix/store/lr2g8s488b3z9bsnfhjw7h5linz306d7-nixtest-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/814c9fi926xrlj777na9pkndqwlqpz80-nixtest-0.1.0.drv' failed to build
```

`singleStep = true` solved my issue! Thanks a lot!!
